# Generated by Django 5.1.5 on 2025-01-20 18:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("WHATSAPP", "WhatsApp"),
                            ("FACEBOOK", "Facebook Messenger"),
                            ("INSTAGRAM", "Instagram"),
                            ("TWITTER", "Twitter"),
                            ("WEB", "Web Widget"),
                            ("MOBILE_SDK", "Mobile SDK"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="platform_icons/"
                    ),
                ),
                (
                    "api_base_url",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "webhook_url",
                    models.CharField(
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("api_version", models.CharField(max_length=20, null=True)),
                ("daily_message_quota", models.IntegerField(default=1000)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_health_check", models.DateTimeField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="chat_platfo_name_a119c0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                ("api_secret", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(null=True)),
                ("additional_credentials", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="chat_platform.chatplatform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("template_code", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField()),
                ("variables", models.JSONField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("approval_status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="chat_platform.chatplatform",
                    ),
                ),
            ],
            options={
                "unique_together": {("platform", "template_code", "language")},
            },
        ),
        migrations.CreateModel(
            name="PlatformHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("response_time", models.FloatField()),
                ("error_count", models.IntegerField(default=0)),
                ("success_rate", models.FloatField()),
                ("messages_sent", models.IntegerField(default=0)),
                ("messages_failed", models.IntegerField(default=0)),
                (
                    "check_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("additional_metrics", models.JSONField(default=dict)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="chat_platform.chatplatform",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "check_timestamp"],
                        name="chat_platfo_platfor_68e52a_idx",
                    )
                ],
            },
        ),
    ]
