# Generated by Django 5.1.5 on 2025-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="employment_details",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="income_range",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age_verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Age Verified"),
                    ("minor", "Verified Minor"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_transaction_limit",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="guardian_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="guardian_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_guardian_notification",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="restricted_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["age_verification_status"],
                name="users_userp_age_ver_a785a4_idx",
            ),
        ),
    ]
