# Generated by Django 5.1.5 on 2025-01-22 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_management", "0002_documenttype"),
        ("users", "0002_remove_userprofile_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Age Verified"),
                            ("minor", "Verified Minor"),
                            ("rejected", "Verification Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verification_document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="age_verifications",
                        to="loan_management.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_age_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_transaction_limit",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "restricted_features",
                    models.JSONField(
                        default=list, help_text="List of restricted features"
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        default=dict, help_text="Guardian notification preferences"
                    ),
                ),
                ("last_notification_sent", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "minor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_control",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["guardian", "minor"],
                        name="users_guard_guardia_34d845_idx",
                    )
                ],
            },
        ),
    ]
