# Generated by Django 5.1.5 on 2025-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_ageverification_guardiancontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
