# Generated by Django 5.1.5 on 2025-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_alter_user_email_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_preference",
            field=models.CharField(
                choices=[
                    ("SMS", "SMS"),
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("IN_APP", "In-App"),
                ],
                default="IN_APP",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("ES", "Spanish"), ("FR", "French")],
                default="EN",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("WHATSAPP", "WhatsApp"),
                    ("INSTAGRAM", "Instagram"),
                ],
                default="FACEBOOK",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
    ]
