# Generated by Django 5.1.5 on 2025-02-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_contact_preference_user_language_user_platform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="username"
            ),
        ),
    ]
