# Generated by Django 5.1.5 on 2025-02-15 13:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="wisrod_account_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Wisrod Client Account ID",
            ),
        ),
    ]
