# Generated by Django 5.1.5 on 2025-01-22 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_chatescalation_chatdocumentsubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("break", "On Break"),
                            ("offline", "Offline"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("max_concurrent_chats", models.IntegerField(default=3)),
                ("current_chats", models.IntegerField(default=0)),
                (
                    "skills",
                    models.JSONField(
                        default=list,
                        help_text="List of agent skills (e.g., ['loans', 'technical', 'billing'])",
                    ),
                ),
                ("last_status_change", models.DateTimeField(auto_now=True)),
                ("auto_assign_enabled", models.BooleanField(default=True)),
                (
                    "working_hours",
                    models.JSONField(
                        default=dict, help_text="Working hours for each day"
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent availabilities",
                "indexes": [
                    models.Index(
                        fields=["status", "current_chats"],
                        name="communicati_status_c39788_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("chats_handled", models.IntegerField(default=0)),
                ("avg_response_time", models.DurationField(null=True)),
                ("avg_resolution_time", models.DurationField(null=True)),
                (
                    "satisfaction_score",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("successful_resolutions", models.IntegerField(default=0)),
                ("escalated_chats", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "agent"], name="communicati_date_51efe7_idx"
                    )
                ],
                "unique_together": {("agent", "date")},
            },
        ),
    ]
