# Generated by Django 5.1.5 on 2025-02-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_platformintegration_platformmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("support", "Support Chat"),
                    ("sales", "Sales Chat"),
                    ("general", "General Inquiry"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
