# Generated by Django 5.1.5 on 2025-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_alter_chatsession_channel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
