# Generated by Django 5.1.5 on 2025-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_chatsession_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="platform",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("facebook", "Facebook Messenger")],
                default="whatsapp",
                max_length=20,
            ),
        ),
    ]
