# Generated by Django 5.1.5 on 2025-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0007_chatsession_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="platform",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook Messenger"),
                    ("web", "Web Chat"),
                ],
                default="whatsapp",
                max_length=20,
            ),
        ),
    ]
