# Generated by Django 5.1.5 on 2025-02-11 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(help_text="Main content/information")),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Key terms or phrases related to this content",
                    ),
                ),
                (
                    "embeddings",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embeddings of the content for semantic search",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the content"
                    ),
                ),
                (
                    "is_training_data",
                    models.BooleanField(
                        default=True,
                        help_text="Use this content for training NLU models",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="1-10 scale, higher number means higher priority",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intelligence.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base Entry",
                "verbose_name_plural": "Knowledge Base Entries",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
