# Generated by Django 5.1.5 on 2025-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_knowledgebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlumodel",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
