# Generated by Django 5.1.5 on 2025-01-21 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("total_chats", models.IntegerField(default=0)),
                ("completed_chats", models.IntegerField(default=0)),
                ("avg_chat_duration", models.FloatField(blank=True, null=True)),
                ("loan_applications", models.IntegerField(default=0)),
                ("approved_loans", models.IntegerField(default=0)),
                ("rejected_loans", models.IntegerField(default=0)),
                ("model_accuracy", models.FloatField(blank=True, null=True)),
                ("system_errors", models.IntegerField(default=0)),
                (
                    "metrics_data",
                    models.JSONField(default=dict, help_text="Additional metrics"),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("chat_started", "Chat Started"),
                            ("chat_completed", "Chat Completed"),
                            ("loan_applied", "Loan Applied"),
                            ("loan_approved", "Loan Approved"),
                            ("loan_rejected", "Loan Rejected"),
                            ("model_trained", "Model Trained"),
                            ("user_registered", "User Registered"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_data", models.JSONField(default=dict)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("platform", models.CharField(blank=True, max_length=50)),
                ("success", models.BooleanField(default=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="monitoring__event_t_3808fe_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="monitoring__user_id_60cecb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                            ("view", "Viewed"),
                            ("export", "Exported"),
                            ("status_change", "Status Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Record of changes made"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="monitoring__content_34d5ac_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="monitoring__action_ea60ab_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="monitoring__user_id_ba8ad7_idx",
                    ),
                ],
            },
        ),
    ]
