# Generated by Django 5.1.5 on 2025-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                ("validation_rules", models.JSONField(default=dict)),
                ("allowed_formats", models.JSONField(default=list)),
                (
                    "max_file_size",
                    models.IntegerField(help_text="Maximum file size in bytes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
